### ISSUE TITLE
Suggestions on README

### ISSUE THREAD

**Issue by tripmonger** [jsheradin/jem_misc#1]
Hi, thanks for pulling this guide together.  A few suggestions to improve the README:

1. According to Hashcode on XDA: https://forum.xda-developers.com/showthread.php?t=2128175

FASTBOOT CABLES ARE NOT REQUIRED FOR USING FASTBOOT MODE ON THE KINDLE FIRE HD 8.9.
POSSIBLE ALSO THAT USING A FASTBOOT CABLE ON THE 8.9 WILL CAUSE DAMAGE.

I am able to boot into fastboot with a regular cable on my Kindle (after installing the proper USB drivers in Windows).

2. In your step 2, you have the following command:
'fastboot flash recovery kfhd8-twrp-2.8.7.0-recovery.img'

However, this isn't one of the files listed to download in step 0. I'm assuming it should be replaced with the following file named "jem_recovery_160403.img"?

3.  In the XDA guide by Hashcode, there seems to be a critical required step missing from the your readme before you flash in fastboot. 

STEP 3. Install the stack override in /system:
`adb push stack /sdcard/`
`adb shell su -c "dd if=/sdcard/stack of=/dev/block/platform/omap/omap_hsmmc.1/by-name/system bs=6519488 seek=1"`

STEP 4. Stop the auto recovery update script (this file may or may not be present):
`adb shell su -c "mount -o remount,rw ext4 /system"`
`adb shell su -c "mv /system/etc/install-recovery.sh /system/etc/install-recovery.sh.bak"`
`adb shell su -c "mount -o remount,ro ext4 /system"`

Have you successfully flashed and installed a new ROM on your Kindle HD 8.9" without step 3 and 4 from Hashcode's guide?

**Comment by jsheradin** [comment]
These were the steps that I used successfully on my tablet. To my knowledge they're valid for all jems. If they don't work on yours let me know.

Thanks for pointing out the recovery file. You're right it should be jem_recovery_160403.img

**Comment by tripmonger** [comment]
I tried the steps in your readme and got to step 2 - flash files. Fastboot said all 3 files flashed OKAY, but when I rebooted, the device got stuck on the Kindle Fire (orange) screen even while I was holding down the up button. So I flashed back to my original boot.img and recovery.img to get the device to boot back into the stock OS.

Are you sure your device didn't already have installed the stack override in STEP 3 of hashcode's guide? My device is not rooted, so I am unable to do this step.

**Comment by jsheradin** [comment]
I never rooted my tablet or installed the stack override. To my knowledge it was stock but who knows.

Try repeatedly pressing the up button during boot. If that doesn't work, try going into fastboot and running `fastboot reboot recovery`.

If that doesn't work, you  can try rooting and installing stack.

**Comment by tripmonger** [comment]
Thanks for the suggestions. I tried both your suggestions to reboot, but my device was still stuck on the Kindle Fire (orange) screen.

I eventually was able to install stack after following this guide to root the device: https://forum.xda-developers.com/kindle-fire-hd/8-9-inch-help/success-rooting-8-5-1-t2943620

After I replaced stack, the device booted into the Kindle Fire (blue) and I was able to install a custom ROM. Let me know if you want me to send you the stack file I used in case you want to add it to this repository for anyone else interested in using it.

Thanks again for putting all of this together in one spot as I found it very useful!

**Comment by jsheradin** [comment]
Thanks for the testing! I'll change the guide to include the step. Was the MD5 of the stack file you used 3cee2b7f3233fc3a1e10373677b8c1a9?

**Comment by tripmonger** [comment]
Yep, MD5 matches the one I used: 3cee2b7f3233fc3a1e10373677b8c1a9

**Comment by jsheradin** [comment]
I've updated the guide to include the missing root and stack override steps. Thanks for testing!
